version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.0
    working_directory: ~/repos
    steps:
      - checkout
      - run:
          command: gem install bundler
      - run:
          command: bundle install
      - run:
          command: bundle exec rubocop
      - run:
          command: bundle exec rake bundle:update
      - run:
          command: bundle exec rake bundle:check
      - run:
          command: bundle exec rake test
