entries:
  - namespace: Ginseng::Web
    path: lib/ginseng/web
  - namespace: Ginseng::Web
    path: lib/ginseng/web/renderer
inflections:
  css_renderer: CSSRenderer
  html_renderer: HTMLRenderer
  http: HTTP
  json_renderer: JSONRenderer
  rss20_feed_renderer: RSS20FeedRenderer
  xml_renderer: XMLRenderer
