inflections:
  ci_test_case_filter: CITestCaseFilter
  css_renderer: CSSRenderer
  html_renderer: HTMLRenderer
  json_renderer: JSONRenderer
  xml_renderer: XMLRenderer
entries:
  - path: lib/ginseng/web
    namespace: Ginseng::Web
  - path: lib/ginseng/web/renderer
    namespace: Ginseng::Web
