package:
  authors:
    - Tatsuya Koishi
  description: ginseng Web libraries
  email:
    - tkoishi@b-shock.co.jp
  license: MIT
  url: https://github.com/pooza/ginseng-web
  version: 1.4.1
puma:
  port: 3014
