package:
  version: 1.3.20
  url: https://github.com/pooza/ginseng-web
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
  description: ginseng Web libraries
  license: MIT
puma:
  port: 3014
