package:
  version: 1.1.2
  url: https://github.com/pooza/ginseng-web
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
  description: ginseng PostgreSQL libraries
  license: MIT
thin:
  port: 3014
